FROM php:8.2-cli

# Installer les extensions nécessaires
RUN apt-get update && apt-get install -y \
    git unzip curl libicu-dev libxml2-dev libzip-dev libonig-dev libpng-dev libjpeg-dev libfreetype6-dev \
    && docker-php-ext-install intl pdo pdo_mysql zip mbstring xml

# Installer Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Créer le dossier de travail
WORKDIR /app

# Copier les fichiers du projet
COPY . .

# Installer les dépendances Symfony
RUN composer install --no-dev --optimize-autoloader

# Exposer le port 8000
EXPOSE 8000

# Lancer Symfony avec le serveur PHP intégré
CMD ["php", "-S", "0.0.0.0:8000", "-t", "public"]
